spring:
  datasource:
    url: jdbc:mysql://10.254.41.72:3306/pyzc_oms_sit?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&allowMultiQueries=true
    username: pyzc_oms_admin
    password: veHadWHQsc
    driver-class-name: com.mysql.cj.jdbc.Driver
    xa:
      properties:
        useInformationSchema: true
file:
  export:
    path: /app/database/view
    version: 0.0.1
    description: "\u76d8\u76c8\u8d44\u4ea7\u6570\u636e\u5e93\u6587\u6863\u751f\u6210"
